namespace Filuet.Hardware.CardReaders.Readers.ICT3K5.Enums
{
    internal enum ICT3K5ErrorCode : uint
    {
        NO_ERROR = 0,
        DEVICE_NOT_CONNECTED_ERROR = 1,
        CANCEL_COMMAND_SESSION_ERROR = 2,
        FAILED_TO_SEND_COMMAND_ERROR = 3,
        FAILED_TO_RECEIVE_REPLY_ERROR = 4,
        COMMAND_CANCELED = 5,
        REPLY_TIMEOUT = 6,
        CANNOT_CREATE_OBJECT_ERROR = 0x101,
        CANNOT_OPEN_DRIVER_ERROR = 0x102,
        FAILED_TO_BEGIN_THREAD_ERROR = 0x103,
        DEVICE_ALREADY_CONNECTED_ERROR = 0x104,
        UPDATE_FIRMWARE_UNEXPECTED_ERROR = 0x1001,
        UPDATE_FIRMWARE_UNKNOWN_FILE_TYPE_ERROR = 0x1002,
        UPDATE_FIRMWARE_CANNOT_OPEN_FILE_ERROR = 0x1003,
        UPDATE_FIRMWARE_FAILED_TO_ALLOCATE_MEMORY_REGION_ERROR = 0x1004,
        UPDATE_FIRMWARE_CANNOT_READ_FILE_ERROR = 0x1005,
        UPDATE_FIRMWARE_CONNECT_DEVICE_FAILED_ERROR = 0x1006,
        UPDATE_FIRMWARE_DEVICE_ALREADY_CONNECTED_ERROR = 0x1007,
        UPDATE_FIRMWARE_COMMAND_EXECUTION_FAILED_ERROR = 0x1008,
        UPDATE_FIRMWARE_NEGATIVE_REPLY_RECEIVED_ERROR = 0x1009,
        UPDATE_FIRMWARE_DISCONNECT_DEVICE_FAILED_ERROR = 0x100a,
        UPDATE_FIRMWARE_UNEXPECTED_FILE_CONTENTS_ERROR = 0x100b,
        UPDATE_FIRMWARE_IDENTICAL_REVISION_ERROR = 0x100c,
        ICC_TRANSMIT_UNEXPECTED_ERROR = 0x2001,
        ICC_TRANSMIT_FAILED_TO_ALLOCATE_MEMORY_REGION_ERROR = 0x2002,
        ICC_TRANSMIT_ABORT_REQUEST_RECEIVED_ERROR = 0x2003,
        ICC_TRANSMIT_COMMAND_EXECUTION_FAILED_ERROR = 0x2004,
        ICC_TRANSMIT_NEGATIVE_REPLY_RECEIVED_ERROR = 0x2005,
        SAM_TRANSMIT_UNEXPECTED_ERROR = 0x3001,
        SAM_TRANSMIT_FAILED_TO_ALLOCATE_MEMORY_REGION_ERROR = 0x3002,
        SAM_TRANSMIT_ABORT_REQUEST_RECEIVED_ERROR = 0x3003,
        SAM_TRANSMIT_COMMAND_EXECUTION_FAILED_ERROR = 0x3004,
        SAM_TRANSMIT_NEGATIVE_REPLY_RECEIVED_ERROR = 0x3005
    }
}